import time
print ("Olá, Bem Vindo ao Ascenção Legado Infernal")
print (input("Insira um nome para iniciar: "))
idade = int(input("Insira sua idade: "))
if idade >= 14:
    print ("Idade aceita!")
else:
    print ("Idade recusada!")
print()
print ("Esse mundo sugiu através da poeira cósmica de uma nebulosa orion...")
time.sleep(5)
print ("Com isso surgiram o Elementais, Smoke, Earth, Mizu e Mac")
time.sleep(5)
print ("Mas não foram somente os elementais que surgiram...")
time.sleep(4)
print ("Maxwell o ser omniversal mais forte de tudo e todos")
time.sleep(5)
print ("E Ercahaya uma ser de luz poderosa")
time.sleep(5)
print ("Nesse jogo você poderá selecionar um personagem dentre os indicados!")
time.sleep(5)
print ("Maxwell - 9000 pontos de vida(HP)")
print ("Elementais - 8500 pontos de vida(HP)")
print ("Ercahaya - 8000 pontos de vida(HP)")
time.sleep(5)
print ("Com seu personagem selecionado, a luta começa!!!")
time.sleep(5)
print ("Ercahaya against Mizu!")
time.sleep(1)
print ("3")
time.sleep(1)
print ("2")
time.sleep(1)
print ("1")
time.sleep(1)
print ("Fight")
time.sleep(1)
print ("Mizu ataca primeiro")
time.sleep(3)
print("Escolha o ataque: Soco, Chute, whirlpool, Hell Water")
ataque = input()
if ataque == "soco":
    print("Você deu um soco no adversário!")
elif ataque == "chute":
    print("Você deu um chute no adversário!")
elif ataque == "whirlpool":
    print("Você acertou o adversário com magia!")
elif ataque == "Hell Water":
    print("Você acertou o adversário com magia!")
else:
    print("Ataque Inválido!")
time.sleep(2)
print ("O ataque removeu 300 HPs do adversário!")
